version: '3.8'

networks:
  my_network:

services:
  backend:
    container_name: my-express-app
    build: .
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - my_network
    volumes:
      - backend_data:/app
    command: ["pnpm", "start"]

  postgres:
    image: postgres:17
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tutoree
    networks:
      - my_network
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "5051:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    depends_on:
      - postgres
    networks:
      - my_network
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  backend_data:
  pgdata:
  pgadmin_data: